# Generated by Django 5.1.3 on 2024-11-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_day_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='meal_image',
            field=models.ImageField(default='./meal_icon.jpg', upload_to='meal_images/'),
        ),
    ]
