# Generated by Django 5.1.3 on 2024-11-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_day_meal_image_meal_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_image',
            field=models.ImageField(default='media/meal_icon.jpg', upload_to='meal_images/'),
        ),
    ]
