# Generated by Django 5.1.3 on 2024-11-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_meal_meal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal_image',
            new_name='mealImage',
        ),
    ]
