# Generated by Django 5.1.3 on 2024-12-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_item_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='allergens',
            field=models.ManyToManyField(related_name='items', to='app.allergen'),
        ),
    ]
