# Generated by Django 5.1.3 on 2024-11-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergen',
            options={'ordering': ['name'], 'verbose_name': 'Allergen', 'verbose_name_plural': 'Allergens'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
