# Generated by Django 5.1.3 on 2024-12-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_item_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
