# Generated by Django 5.1.3 on 2025-01-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_meal_mealimage'),
        ('app', '0015_remove_meal_mealimage_alter_item_allergens'),
    ]

    operations = [
    ]
